# Generated by Django 2.2.7 on 2020-01-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databaseinformation',
            name='id1',
        ),
        migrations.AddField(
            model_name='databaseinformation',
            name='abv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='databaseinformation',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='databaseinformation',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
