# Generated by Django 2.2.7 on 2020-01-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0002_auto_20200128_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseinformation',
            name='img',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
