# Generated by Django 2.2.7 on 2020-01-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0005_auto_20200128_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseinformation',
            name='abv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='databaseinformation',
            name='description',
            field=models.TextField(default=100, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='databaseinformation',
            name='name',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
