# Generated by Django 2.2.7 on 2020-01-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0007_auto_20200128_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseinformation',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
