# Generated by Django 2.2.7 on 2020-01-29 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0011_auto_20200129_1156'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BeerData',
            new_name='DatabaseInformation',
        ),
    ]
