# Generated by Django 2.2.7 on 2020-01-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0012_auto_20200129_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreweryInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
