# Generated by Django 2.2.7 on 2020-01-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0009_auto_20200128_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseinformation',
            name='abv',
            field=models.FloatField(),
        ),
    ]
