# Generated by Django 2.2.7 on 2020-01-29 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0010_auto_20200128_1801'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DatabaseInformation',
            new_name='BeerData',
        ),
    ]
