# Generated by Django 2.2.7 on 2020-02-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0013_breweryinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='breweryinformation',
            name='img',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='databaseinformation',
            name='img',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='databaseinformation',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
