# Generated by Django 2.2.7 on 2020-02-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0015_auto_20200208_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breweryinformation',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
