# Generated by Django 2.2.7 on 2020-02-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0016_auto_20200208_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breweryinformation',
            name='description',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='databaseinformation',
            name='description',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
