# Generated by Django 2.2.7 on 2020-02-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0017_auto_20200208_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseinformation',
            name='rate',
            field=models.IntegerField(null=True),
        ),
    ]
