# Generated by Django 2.2.7 on 2020-03-18 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Database', '0025_nonalcoholic'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseinformation',
            name='likes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
