# Generated by Django 2.2.7 on 2020-03-18 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0026_databaseinformation_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseinformation',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
