# Generated by Django 2.2.7 on 2020-03-23 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0027_auto_20200318_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databaseinformation',
            name='likes',
        ),
    ]
